### ISSUE TITLE
Darwin tries to load `liby_rb.dylib` but lib is named `y_rb.dylib`

### ISSUE THREAD

**Issue by eliias** [y-crdt/yrb#17]
# Problem

 In case `cargo` isn't available, we successfully download the archive for the platform, but after unpacking it does not present the library with the expected name.
 
# Solution

The archive should contain the file with the correct name.

**Comment by ianks** [comment]
FWIW, rb-sys will fix this. On darwin Ruby actually looks for `.bundle` files, and they need to be binary compatible. It can become a rabbit hole.

Using `rb-sys` with `rake-compiler` will handle this nicely.

**Comment by eliias** [comment]
Port to magnus/rb-sys is tracked in this branch https://github.com/y-crdt/yrb/tree/migrate-to-magnus.

**Comment by eliias** [comment]
Port to `magnus` is working, this is going to be resolved by the migration.
