### ISSUE TITLE
Update build instructions

### ISSUE THREAD

**Issue by mttkay** [y-crdt/yrb#84]
The instructions in README are not working for me; I was on Ruby 3.0.5, which ships `rubygems`  3.2.33. `rubygems` is an stdlib gem bundled with the Ruby platform: https://stdgems.org/rubygems/

```
[9:34:53] work/yrb::main ✔ bundle install
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Could not find compatible versions

Because every version of y-rb depends on RubyGems >= 3.3.21
  and Gemfile depends on y-rb >= 0,
  RubyGems >= 3.3.21 is required.
So, because current RubyGems version is = 3.2.33,
  version solving has failed.
```

The docs currently mention to manually update rubygems to 3.3.x via `gem system --update` but this command does not seem to exist:

```
[9:38:21] work/yrb::main ✔ gem system --update  
ERROR:  While executing gem ... (Gem::UnknownCommandError)
    Unknown command system
```

What I did instead is to switch my shell Ruby to 3.1+ which bundles the necessary version of rubygems (3.3.x).

I am not sure whether or how one should update rubygems beyond the version shipped with Ruby itself; should we instead document the minimum Ruby to be 3.1, which ships with rubygems 3.3.3 by default? That fixes the build problems for me, but of course that would imply older Rubies are not supported. This may be OK, considering that the 3.0 line of Rubies will reach EOL in about a year from now: https://endoflife.date/ruby

**Comment by eliias** [comment]
Yeah, the command is actually `gem update --system` 🤦. I have fixed the README.

In terms of Ruby support, the gem currently ships with pre-built binaries for 2.7, 3.0, 3.1, and 3.2 and my plan is to remove rubies when they hit EOL. e.g. 2.7 should not be included in any release after next month, 3.0 should be removed next year, etc.
